[platformio]
default_envs = t5s3-pro-bench

[env:t5s3-pro]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 460800

board_upload.flash_size = 16MB
board_upload.maximum_size = 6553600
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.filesystem = littlefs
board_build.partitions = partitions/t5s3_pro_factory_layout.csv

build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_RUNNING_CORE=1
    -D ARDUINO_EVENT_RUNNING_CORE=1
    -D CORE_DEBUG_LEVEL=0
    -Wno-return-type
    -D MNEMOS_T5S3_PRO=1
    -D MNEMOS_EXTERNAL_I2C_DRIVER=1

lib_deps =
    bblanchon/ArduinoJson @ ^7
    https://github.com/ricmoo/QRCode.git
    lewisxhe/SensorLib @ ^0.4.1

[env:t5s3-pro-bench]
extends = env:t5s3-pro
build_flags =
    ${env:t5s3-pro.build_flags}
    -D MNEMOS_BENCH_BUILD=1

[env:t5s3-pro-bench-demo]
extends = env:t5s3-pro-bench
build_flags =
    ${env:t5s3-pro-bench.build_flags}
    -D MNEMOS_DEMO_INTERVALS=1

[env:t5s3-pro-bench-ota-source]
extends = env:t5s3-pro-bench
build_flags =
    ${env:t5s3-pro-bench.build_flags}
    -D MNEMOS_OTA_TEST_SOURCE=1

[env:t5s3-pro-bench-ota-target]
extends = env:t5s3-pro-bench
build_flags =
    ${env:t5s3-pro-bench.build_flags}
    -D MNEMOS_OTA_TEST_TARGET=1
