[env:lilygo-t5-47-s3]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.filesystem = littlefs
board_build.partitions = partitions/mnemos_t5_ota.csv

build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_RUNNING_CORE=1
    -D ARDUINO_EVENT_RUNNING_CORE=1
    -D CORE_DEBUG_LEVEL=0

lib_deps =
    bblanchon/ArduinoJson @ ^7
    https://github.com/ricmoo/QRCode.git
    https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git#esp32s3
    lewisxhe/SensorLib @ ^0.4.1
